# Use postgres 9.5
FROM postgres:9.5

# Creates database with name "dataspread_db" and superuser with username "admin" and password "password"
# Any changes to these values should also be made to the "jdbc/ibd" Resource in context.xml
ENV POSTGRES_DB dataspread_db
ENV POSTGRES_USER admin  
ENV POSTGRES_PASSWORD password  